### ISSUE TITLE
Alt-Tab Multimonitor

### ISSUE THREAD

**Issue by dgerblick** [ViliamKovac1223/dwm-ViliamKovac1223-build#1]
Using the Alt-Tab patch on a multi-monitor setup causes the tabwin to appear in the wrong area. Changing drawTab to consider the mx and my of the selected monitor fixes this issue. [I created a new patch](https://gist.github.com/dgerblick/959cc71b97dd08a9e5e9f4f6bad13b9e) with the change. Figured I'd share this here just in case anyone else ran into the same issue.

**Comment by ViliamKovac1223** [comment]
Nice work. I will merge this to main branch here on github and upload a patch on suckless official web site.
I will add you to contributors on suckless website if you don't mind this for privacy reasons.

**Comment by dgerblick** [comment]
I don't mind at all!
