### ISSUE TITLE
[Feature Request] Closing menu with Escape key

### ISSUE THREAD

**Issue by mhdna** [ViliamKovac1223/dwm-ViliamKovac1223-build#3]
Hello,
Thanks a lot for your super useful alt-tab dwm patch.
It would be nice to have the menu close using Escape key like it does in other alt-tab implementations.

Thanks in advance!

**Comment by ViliamKovac1223** [comment]
Hi,
Apologies for the late response. College has kept me quite busy lately.

I've found your feature request really interesting, so I went ahead and implemented and I've created a new patch for the repository.
The patch will come to the suckless webpage later. 

You can checkout the changes and leave me feedback. If everything is okay we can close issue and I will add patch to the suckless webpage.

**Comment by mhdna** [comment]
Yeah, Everything works just fine, and there doesn't seem to be any issues.

May Allah bless you with success in your college, and thank you Villiam so much for your time.
