### ISSUE TITLE
[restoreafterrestart] Issue with multimonitors 

### ISSUE THREAD

**Issue by nullbyto** [ViliamKovac1223/dwm-ViliamKovac1223-build#4]
Hello, 
I use your `restoreafterrestart` patch, works really great on one monitor.

The only problem is when using multiple monitors, the windows from second monitor come into the tag 1 in the primary monitor. I was not able to fix this issue.
It would be great to add this into the patch.

Thank you for your time.

**Comment by ViliamKovac1223** [comment]
Hi,
I would like to add this but I don't have multiple monitors to test/develop this. So for the time being this will not be added.
